import { formatDate, parseLocalDate } from '../config.js';
import * as globalIndexMd  from '../global-index-md.js';
import * as projectIndexMd from '../project-index-md.js';
import * as log from '../logger.js';

// ---------------------------------------------------------------------------
// milestone add: append a new H2 milestone section to project-index.md
// ---------------------------------------------------------------------------

function add(workspace, opts) {
  if (!opts.id)   { throw new Error('ERROR: --id is required');   }
  if (!opts.name) { throw new Error('ERROR: --name is required'); }
  if (!opts.due)  { throw new Error('ERROR: --due is required');  }
  parseLocalDate(opts.due); // validates; throws on invalid

  const projects = globalIndexMd.readGlobalIndex(workspace);
  const proj     = projects.find(p => p.id === opts.id);
  if (!proj) { throw new Error(`ERROR: Project '${opts.id}' not found`); }

  // Read live project data and check for duplicates
  const data = projectIndexMd.read(proj.path);
  if (data.milestones.some(m => m.name === opts.name)) {
    throw new Error(`ERROR: Milestone '${opts.name}' already exists in project '${opts.id}'`);
  }

  // addMilestone handles lockfile and writes project-index.md.
  // WHY no loadIndex/saveIndex: milestones now live only in the project body.
  // The global index is regenerated by sweep; individual operations touch only
  // the per-project file.
  const newMilestone = projectIndexMd.addMilestone(proj.path, {
    name: opts.name,
    due:  opts.due,
  });

  log.info('milestone added', { projectId: opts.id, name: opts.name, due: opts.due, uuid: newMilestone.uuid });
  console.log(`Milestone '${opts.name}' added to ${opts.id} (due ${opts.due})`);
}

// ---------------------------------------------------------------------------
// milestone complete: mark a milestone's tasks as complete (or note completion)
// ---------------------------------------------------------------------------

function complete(workspace, opts) {
  if (!opts.id)   { throw new Error('ERROR: --id is required');   }
  if (!opts.name) { throw new Error('ERROR: --name is required'); }

  const projects = globalIndexMd.readGlobalIndex(workspace);
  const proj     = projects.find(p => p.id === opts.id);
  if (!proj) { throw new Error(`ERROR: Project '${opts.id}' not found`); }

  const data      = projectIndexMd.read(proj.path);
  const milestone = data.milestones.find(m => m.name === opts.name);
  if (!milestone) {
    throw new Error(`ERROR: Milestone '${opts.name}' not found in project '${opts.id}'`);
  }

  // A milestone is logically "completed" when all its tasks are done.
  // In the body format there is no separate milestone-level completedDate;
  // instead we track whether all tasks are completed.
  // WHY: the spec stores milestone data only in the body. To mark a milestone
  // complete, we mark all its tasks as completed.
  const allCompleted = milestone.tasks.every(t => t.status === 'completed');
  if (allCompleted && milestone.tasks.length > 0) {
    console.warn(`WARN: Milestone '${opts.name}' is already completed`);
    log.warn('milestone already completed', { projectId: opts.id, name: opts.name });
    return;
  }

  const dateStr = formatDate(new Date(), '-');
  for (const task of milestone.tasks) {
    if (task.status !== 'completed') {
      task.status      = 'completed';
      task.completedAt = dateStr;
    }
  }

  projectIndexMd.write(proj.path, data);

  log.info('milestone completed', { projectId: opts.id, name: opts.name, completedDate: dateStr });
  console.log(`Milestone '${opts.name}' completed (${dateStr})`);
}

export { add, complete };
